site_name: M133 - PHP

theme:
    name: material
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              icon: material/weather-night
              name: Switch to light mode
    language: de
    font:
        text: Roboto
    icon:
        repo: fontawesome/brands/github-alt
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.top
        - navigation.indexes
        - search.share
        - content.code.annotate
        - content.tabs.link

extra_css:
    - assets/css/custom.css

copyright: Copyright &copy; 2022 Doku Autor

repo_url: https://github.com/bztfinformatik/lernportfolio-21r9149-php
repo_name: 21r9149/Sourcecode
edit_uri: https://github.com/bztfinformatik/lernportfolio-21r9149-php/tree/master/docs

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/bztfinformatik/lernportfolio-21r9149-php
          name: 21r9149 on GitHub

markdown_extensions:
    # Python Markdown
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - md_in_html
    - toc:
          permalink: "#"
    - pymdownx.emoji:
          emoji_generator: !!python/name:materialx.emoji.to_svg
          emoji_index: !!python/name:materialx.emoji.twemoji

    - pymdownx.arithmatex:
          generic: true
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.snippets:
          base_path: docs
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.tasklist:
          custom_checkbox: true

plugins:
    - search:
          lang:
              - de
    - tags:
          tags_file: "Tags.md"
#     - redirects:
#           redirect_maps:
#               "Inhaltsverzeichnis.md": "Tags.md"

nav:
    - Startseite:
          - Startseite: "index.md"
          - Inhaltsverzeichnis: "Tags.md"
    - Reflexion:
          - Tag 1: "reflexion/01.md"
          - Tag 2: "reflexion/02.md"
          - Tag 3: "reflexion/03.md"
          - Tag 4: "reflexion/04.md"
          - Tag 5: "reflexion/05.md"
          - Tag 6: "reflexion/06.md"
          - Tag 7: "reflexion/07.md"
          - Tag 8: "reflexion/08.md"
          - Tag 9: "reflexion/09.md"
          - Tag 10: "reflexion/10.md"
          - Tag 11: "reflexion/11.md"
    - PHP:
          - PHP Grundlagen: "php/php_grundlagen.md"
          - Rechnen mit Variablen: "php/rechnen_mit_variablen.md"
          - $_GET und $_POST: "php/get_and_post.md"
          - Arrays: "php/arrays.md"
          - Formulare mit $_Get und $_Post: "php/formulare_get_and_post.md"
          - Arbeitsweise mit Datentypen: "php/arbeitsweise_mit_datentypen.md"
          - Kontrollstrukturen: "php/kontrollstrukturen.md"
          - Arbeiten mit Dateien: "php/arbeiten_mit_dateien.md"
          - OOP: "php/oop.md"
          - MVC: "php/mvc.md"
          - MVC 101: "php/mvc_101.md"
          - Twig Template: "php/twig_template.md"
          - Sessions & Cookies: "php/session_and_cookies.md"
          
    - LB1:
          - 1. Abgabe: "LB1/abgabe1.md"
          - 2. Abgabe: "LB1/abgabe2.md"
          - 3. Abgabe: "LB1/abgabe3.md"
          - 4. Testfälle: "LB1/testfaelle.md"
    - LB2:
          - Concept-Map 1: "LB2/concept_map.md"
          - Concept-Map 2: "LB2/concept_map2.md"
          - Concept-Map 3: "LB2/concept_map3.md"
    - Appendix:
          - Docker Grundlagen: "appendix/docker.md"
          - 1. Programmierauftrag: "appendix/01programmierauftrag.md"
          - 2. Programmierauftrag: "appendix/02programmierauftrag.md"
          - SSR & CSR: "appendix/SSR_&_CSR.md"
          - Regex: "appendix/regex.md"
